version: "3"
services:
  mdr-notes:
    container_name: mdr-notes
    image: mdr-notes
    build:
      context: .
      dockerfile: Dockerfile
  letsencrypt:
    image: lscr.io/linuxserver/swag
    container_name: le
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart: always
    depends_on:
      - mdr-notes
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=maurits.de.roover@outlook.com
      - URL=mdr-tools.com
      - SUBDOMAINS = www
      - DHLEVEL=4096
      - TZ=Europe/London