/**
 * Generated by the artifact generator [@inrupt/artifact-generator], version [1.0.4]
 * as part of artifact: [generated-vocab-notetaking], version: [0.0.1]
 * on 'Wednesday, April 6, 2022 8:20 PM'.
 *
 * Vocabulary built from input: [https://mauritsderoover.solidcommunity.net/public/notetaking.ttl].
 *
 * [Generator provided] - undefined
 */

/* eslint-disable */

// We prefix our local variables with underscores to (hopefully!) prevent
// potential names clashes with terms from vocabularies.
const { VocabTerm: _VocabTerm, getLocalStore } = require("@inrupt/solid-common-vocab");
const _DataFactory = require("@rdfjs/data-model");

const { namedNode: _namedNode } = _DataFactory;

function _NS(localName: string) {
  return _namedNode(`https://mauritsderoover.solidcommunity.net/public/notetaking/${localName}`);
}

/**
 * [Generator provided] - undefined
 */
const NOTETAKING = {
  PREFIX: "notetaking",
  NAMESPACE: "https://mauritsderoover.solidcommunity.net/public/notetaking/",
  PREFIX_AND_NAMESPACE: { "notetaking": "https://mauritsderoover.solidcommunity.net/public/notetaking/" },
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * Note Content is the content that belongs to a note page. A note page can have multiple note content entities
   *
   * The term has a description only in English, but has a mismatch between its labels and comments, with [0] labels, but [1] comment in the language [en].
   */
  NoteContent: new _VocabTerm(
    _NS("NoteContent"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addComment(`Note Content is the content that belongs to a note page. A note page can have multiple note content entities`, "en"),

  /**
   * A group of a pages containing notes
   *
   * The term has a description only in English, but has a mismatch between its labels and comments, with [0] labels, but [1] comment in the language [en].
   */
  PageGroup: new _VocabTerm(
    _NS("PageGroup"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addComment(`A group of a pages containing notes`, "en"),

  /**
   * A section is a group or category of notes that belong together. A section can belong to a section group.
   *
   * This term provides multilingual descriptions, but has a mismatch between its labels and comments, with [3] labels in languages [de, en, nl], but [1] comment in the language [en].
   */
  Section: new _VocabTerm(
    _NS("Section"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`Abschnitt`, "de")
    .addLabel(`Section`, "en")
    .addLabel(`Sectie`, "nl")
    .addComment(`A section is a group or category of notes that belong together. A section can belong to a section group.`, "en"),

  /**
   * A note are thoughts written down primarily meant for the author of the note.
   *
   * This term provides multilingual descriptions, but has a mismatch between its labels and comments, with [3] labels in languages [de, en, nl], but [1] comment in the language [en].
   */
  Note: new _VocabTerm(
    _NS("Note"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`Seite`, "de")
    .addLabel(`Page`, "en")
    .addLabel(`Pagina`, "nl")
    .addComment(`A note are thoughts written down primarily meant for the author of the note.`, "en"),

  /**
   * A notebook is a collection of notes, note groups, sections, section groups
   *
   * This term provides multilingual descriptions, but has a mismatch between its labels and comments, with [3] labels in languages [de, en, nl], but [1] comment in the language [en].
   */
  NoteBook: new _VocabTerm(
    _NS("NoteBook"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`Notizbuch`, "de")
    .addLabel(`Notebook`, "en")
    .addLabel(`Notitieblok`, "nl")
    .addComment(`A notebook is a collection of notes, note groups, sections, section groups`, "en"),

  /**
   * A group of sections containing notes
   *
   * This term provides multilingual descriptions, but has a mismatch between its labels and comments, with [3] labels in languages [de, en, nl], but [1] comment in the language [NoLocale].
   */
  SectionGroup: new _VocabTerm(
    _NS("SectionGroup"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`Abschnittgruppe`, "de")
    .addLabel(`Sectiongroup`, "en")
    .addLabel(`Sectiegroep`, "nl")
    .addCommentNoLanguage(`A group of sections containing notes`),


  // *******************
  // All the Properties.
  // *******************

  /**
   * The horizontal distance of a pageContent with respect to the parent div from the left
   *
   * The term has a description only in English, but has a mismatch between its labels and comments, with [0] labels, but [1] comment in the language [en].
   */
  distanceLeft: new _VocabTerm(
    _NS("distanceLeft"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addComment(`The horizontal distance of a pageContent with respect to the parent div from the left`, "en"),

  /**
   * The distance of a contentDiv compared to the top of its parentDiv
   *
   * The term has a description only in English, but has a mismatch between its labels and comments, with [0] labels, but [1] comment in the language [en].
   */
  distanceTop: new _VocabTerm(
    _NS("distanceTop"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addComment(`The distance of a contentDiv compared to the top of its parentDiv`, "en"),

  /**
   * A page that is part of a section or a page group
   *
   * This term provides descriptions only in English.
   */
  hasPage: new _VocabTerm(
    _NS("hasPage"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`hasPage`, "en")
    .addComment(`A page that is part of a section or a page group`, "en"),

  /**
   * The content that belongs to a specific note page
   *
   * This term provides descriptions only in English.
   */
  hasPageContent: new _VocabTerm(
    _NS("hasPageContent"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`hasPageContent`, "en")
    .addComment(`The content that belongs to a specific note page`, "en"),

  /**
   * A page group that belongs to a section
   *
   * This term provides descriptions only in English.
   */
  hasPageGroup: new _VocabTerm(
    _NS("hasPageGroup"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`hasPageGroup`, "en")
    .addComment(`A page group that belongs to a section`, "en"),

  /**
   * A section that belongs to a sectiongroup or a notebook
   *
   * This term provides descriptions only in English.
   */
  hasSection: new _VocabTerm(
    _NS("hasSection"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`hasSection`, "en")
    .addComment(`A section that belongs to a sectiongroup or a notebook`, "en"),

  /**
   * A notebook can have a sectiongroup
   *
   * This term provides descriptions only in English.
   */
  hasSectionGroup: new _VocabTerm(
    _NS("hasSectionGroup"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`hasSectionGroup`, "en")
    .addComment(`A notebook can have a sectiongroup`, "en"),

  /**
   * The notebook to which this section or section group belongs.
   *
   * This term provides descriptions only in English.
   */
  partOfNoteBook: new _VocabTerm(
    _NS("partOfNoteBook"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`partOfNoteBook`, "en")
    .addComment(`The notebook to which this section or section group belongs.`, "en"),

  /**
   * The page group to which this page belongs.
   *
   * This term provides descriptions only with no explicit locale.
   */
  partOfPageGroup: new _VocabTerm(
    _NS("partOfPageGroup"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`partOfPageGroup`)
    .addCommentNoLanguage(`The page group to which this page belongs.`),

  /**
   * The section to which this page or this group of pages belongs.
   *
   * This term provides descriptions only in English.
   */
  partOfSection: new _VocabTerm(
    _NS("partOfSection"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabel(`partOfSection`, "en")
    .addComment(`The section to which this page or this group of pages belongs.`, "en"),

  /**
   * The section group to which this section belongs.
   *
   * This term provides descriptions only with no explicit locale.
   */
  partOfSectionGroup: new _VocabTerm(
    _NS("partOfSectionGroup"),
    _DataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`partOfSectionGroup`)
    .addCommentNoLanguage(`The section group to which this section belongs.`),

}

export default NOTETAKING;
